---
- name: "Centos 7 LAMP Installation"
  hosts: 127.0.0.1
  connection: local
  vars_files: /root/LAMPforcentos/group_vars/centos7.yml
  become: true
  become_method: sudo
  become_user: root
  roles:
    - apache
    - php
    - mysql
