---
- name: "MariaBD install"
  yum:
    name: ["mariadb", "mariadb-server", "python2-PyMySQL", "python36-PyMySQL"]
    state: present

- name: "MariaDB Start and Enable"
  ansible.builtin.service:
    name: mariadb
    state: restarted
    enabled: yes

# Set your secrets into vars
- name: "MariaDB set to work"
  mysql_user:
    login_user: root
    login_password: "{{ password_root }}"
    user: root
    check_implicit_admin: true
    password: "{{ password_root }}"
    host: localhost

    
